// Generated by sqlboiler-erg: DO NOT EDIT.
package erg

import (
	"github.com/wearepointers/tycho/example/models/dm"
)

type TablesWithColumns map[string]map[string]bool

var TablesWithColumnsMap = TablesWithColumns{
	dm.TableNames.Account: map[string]bool{
		dm.AccountColumns.ID:        true,
		dm.AccountColumns.FirstName: true,
		dm.AccountColumns.LastName:  true,
		dm.AccountColumns.Email:     true,
		dm.AccountColumns.CreatedAt: true,
		dm.AccountColumns.UpdatedAt: true,
		dm.AccountColumns.DeletedAt: true,
	},
	dm.TableNames.AccountSession: map[string]bool{
		dm.AccountSessionColumns.ID:        true,
		dm.AccountSessionColumns.AccountID: true,
		dm.AccountSessionColumns.IPAddress: true,
		dm.AccountSessionColumns.UserAgent: true,
		dm.AccountSessionColumns.ExpiresAt: true,
		dm.AccountSessionColumns.CreatedAt: true,
		dm.AccountSessionColumns.UpdatedAt: true,
		dm.AccountSessionColumns.DeletedAt: true,
	},
	dm.TableNames.Comment: map[string]bool{
		dm.CommentColumns.ID:             true,
		dm.CommentColumns.OrganizationID: true,
		dm.CommentColumns.EventID:        true,
		dm.CommentColumns.AccountID:      true,
		dm.CommentColumns.Comment:        true,
		dm.CommentColumns.CreatedAt:      true,
		dm.CommentColumns.UpdatedAt:      true,
		dm.CommentColumns.DeletedAt:      true,
	},
	dm.TableNames.Event: map[string]bool{
		dm.EventColumns.ID:             true,
		dm.EventColumns.OrganizationID: true,
		dm.EventColumns.AccountID:      true,
		dm.EventColumns.Name:           true,
		dm.EventColumns.Description:    true,
		dm.EventColumns.CreatedAt:      true,
		dm.EventColumns.UpdatedAt:      true,
		dm.EventColumns.DeletedAt:      true,
	},
	dm.TableNames.Organization: map[string]bool{
		dm.OrganizationColumns.ID:        true,
		dm.OrganizationColumns.Name:      true,
		dm.OrganizationColumns.CreatedAt: true,
		dm.OrganizationColumns.UpdatedAt: true,
		dm.OrganizationColumns.DeletedAt: true,
	},
	dm.TableNames.OrganizationAccount: map[string]bool{
		dm.OrganizationAccountColumns.ID:             true,
		dm.OrganizationAccountColumns.OrganizationID: true,
		dm.OrganizationAccountColumns.AccountID:      true,
		dm.OrganizationAccountColumns.Role:           true,
		dm.OrganizationAccountColumns.CreatedAt:      true,
		dm.OrganizationAccountColumns.UpdatedAt:      true,
		dm.OrganizationAccountColumns.DeletedAt:      true,
	},
}

func TableHasColumn(tableName, columnName string) bool {
	if _, ok := TablesWithColumnsMap[tableName]; !ok {
		return false
	}

	if _, ok := TablesWithColumnsMap[tableName][columnName]; !ok {
		return false
	}

	return true
}
