// Generated by sqlboiler-erg: DO NOT EDIT.
package erg

import (
	"github.com/wearepointers/tycho/example/models/dm"
	"time"
)

type Organization struct {
	ID        string     `json:"id,omitempty" toml:"id" yaml:"id"`
	Name      string     `json:"name,omitempty" toml:"name" yaml:"name"`
	CreatedAt time.Time  `json:"createdAt,omitempty" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time  `json:"updatedAt,omitempty" toml:"updated_at" yaml:"updated_at"`
	DeletedAt *time.Time `json:"deletedAt,omitempty" toml:"deleted_at" yaml:"deleted_at"`

	Events               EventSlice               `json:"events,omitempty" toml:"events" yaml:"events"`
	OrganizationAccounts OrganizationAccountSlice `json:"organizationAccounts,omitempty" toml:"organization_accounts" yaml:"organization_accounts"`

	CustomFields `json:"customFields,omitempty" toml:"custom_fields" yaml:"custom_fields"`
}

type OrganizationSlice []*Organization

func ToOrganizations(a dm.OrganizationSlice, acf CustomFieldsSlice, exclude ...string) OrganizationSlice {
	s := make(OrganizationSlice, len(a))
	for i, d := range a {
		var cf CustomFields
		if acf != nil {
			if value, ok := acf[d.ID]; ok {
				cf = value
			}
		}

		s[i] = ToOrganization(d, cf, exclude...)
	}
	return s
}

func ToOrganization(a *dm.Organization, customFields CustomFields, exclude ...string) *Organization {
	p := Organization{
		ID:        a.ID,
		Name:      a.Name,
		CreatedAt: a.CreatedAt,
		UpdatedAt: a.UpdatedAt,
		DeletedAt: nullDotTimeToTimePtr(a.DeletedAt),
	}

	if a.R != nil {
		if a.R.Events != nil && doesNotContain(exclude, "organization.event") {
			p.Events = ToEvents(a.R.Events, nil, append(exclude, "event.organization")...)
		}
		if a.R.OrganizationAccounts != nil && doesNotContain(exclude, "organization.organization_account") {
			p.OrganizationAccounts = ToOrganizationAccounts(a.R.OrganizationAccounts, nil, append(exclude, "organization_account.organization")...)
		}
	}

	if customFields != nil {
		p.CustomFields = customFields
	}

	return &p
}
