// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dm

var TableNames = struct {
	Account             string
	AccountSession      string
	Comment             string
	Event               string
	Organization        string
	OrganizationAccount string
	SchemaMigrations    string
}{
	Account:             "account",
	AccountSession:      "account_session",
	Comment:             "comment",
	Event:               "event",
	Organization:        "organization",
	OrganizationAccount: "organization_account",
	SchemaMigrations:    "schema_migrations",
}
